[package]
name = "cpuv"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
egui_extras = "0.29.1"
env_logger = "0.11.5"
structmap = "0.1.6"
structmap-derive = "0.1.6"

[profile.release]
opt-level = 3
