[package]
name = "irv"
version = "0.1.0"
edition = "2024"
description = "The Intermediate Representation for the CPU-V Platform"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
